# Generated by Django 6.0.3 on 2026-03-31 19:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_updated_at_alter_service_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_joined', models.IntegerField(default=0)),
                ('total_served', models.IntegerField(default=0)),
                ('total_cancelled', models.IntegerField(default=0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'date')},
            },
        ),
    ]
