# Generated by Django 6.0.3 on 2026-03-29 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0002_alter_service_avg_service_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_joined', models.IntegerField(default=0)),
                ('total_served', models.IntegerField(default=0)),
                ('total_cancelled', models.IntegerField(default=0)),
                ('avg_wait_time', models.FloatField(default=0.0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'date')},
            },
        ),
    ]
