# Generated by Django 6.0.3 on 2026-03-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='avg_service_time',
            field=models.IntegerField(default=10, help_text='Average time in minutes'),
        ),
    ]
