# Generated by Django 6.0.3 on 2026-03-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('done', 'Done'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('called', 'CALLED')], default='waiting', max_length=20),
        ),
    ]
